/**
 * The brand profile and the downloadable Brand Kit (§17, §19).
 *
 * The kit matters more than it looks. A founder who can hand a printer a PDF
 * with the hex codes, the fonts and the clear-space rule gets back what they
 * asked for; a founder who sends a screenshot of a logo gets back a guess. This
 * is the artefact that makes the brand *portable* — the thing that outlives
 * Brandora's own interface.
 */

import {
  type BrandProfile,
  type ColorSwatch,
  type Locale,
  type Typography,
  newId,
  slugify,
} from "@brandora/shared";
import type { BrandBrief } from "./interview.js";
import type { BrandStrategy } from "./strategy.js";
import { buildLogoBrief, derivePalette, deriveTypography, type IdentityOptions } from "./identity.js";

export interface AssembleOptions extends IdentityOptions {
  now?: Date;
  brandId?: string;
}

/**
 * Fold the interview, the generated words and the derived visuals into the one
 * row everything else reads from — the catalogue, the assistant, the quote.
 */
export function assembleBrandProfile(
  userId: string,
  brief: BrandBrief,
  strategy: BrandStrategy,
  options: AssembleOptions = {},
): BrandProfile {
  const palette = derivePalette(brief, options);
  const typography = deriveTypography(brief);
  const timestamp = (options.now ?? new Date()).toISOString();

  return {
    id: options.brandId ?? newId("brand"),
    userId,
    name: strategy.name,
    description: strategy.description,
    industry: strategy.industry,
    targetCustomer: strategy.targetCustomer,
    positioning: strategy.positioning,
    personality: strategy.personality,
    promise: strategy.promise,
    mission: strategy.mission,
    vision: strategy.vision,
    slogan: strategy.slogan,
    toneOfVoice: strategy.toneOfVoice,
    brandStory: strategy.brandStory,
    palette,
    typography,
    logoBrief: buildLogoBrief(brief, palette, typography, strategy.name),
    status: "generated",
    locale: (brief.locale as Locale) ?? "en",
    createdAt: timestamp,
    updatedAt: timestamp,
  };
}

/* --- Guidelines ---------------------------------------------------------- */

const clearSpaceRule =
  "Leave clear space around the logo equal to the height of its symbol. Nothing — no text, no edge, no other logo — enters that space.";

/**
 * The guidelines document, as Markdown.
 *
 * Written as instructions a supplier can follow, not as a design essay. Every
 * section answers a question someone actually asks when producing something:
 * which colour, how big, how much space, what not to do.
 */
export function buildGuidelines(profile: BrandProfile): string {
  const swatch = (c: ColorSwatch): string => `| ${c.name} | \`${c.hex}\` | ${c.rationale} |`;
  const type = (t: Typography): string =>
    `**Headings —** ${t.primary} (fallback: ${t.primaryFallback})\n\n**Body —** ${t.secondary} (fallback: ${t.secondaryFallback})\n\n${t.rationale}`;

  return `# ${profile.name} — Brand Guidelines

*${profile.slogan}*

## What we are

${profile.description}

**Who we serve.** ${profile.targetCustomer}

**Our promise.** ${profile.promise}

**Positioning.** ${profile.positioning.replace("-", " ")}

**Personality.** ${profile.personality.join(" · ")}

## Story

${profile.brandStory}

**Mission.** ${profile.mission}

**Vision.** ${profile.vision}

## Voice

${profile.toneOfVoice}

## Colour

| Colour | Hex | Where to use it |
| --- | --- | --- |
${profile.palette.map(swatch).join("\n")}

Give a printer the hex codes above. If they ask for CMYK or Pantone, ask them to
match to the hex rather than converting by eye — conversions drift, and the drift
shows up when two suppliers print the same colour.

## Typography

${type(profile.typography)}

## Logo

${profile.logoBrief}

**Clear space.** ${clearSpaceRule}

**Minimum size.** 16px tall on screen, 8mm tall in print. Below that, use the
symbol alone rather than the full lockup.

**Don't:** stretch it, add a shadow, place it on a busy photograph, recolour it
outside this palette, or rebuild it in a different typeface.

---

Generated by Brandora — build your brand, put it everywhere.
`;
}

/* --- Kit ----------------------------------------------------------------- */

export interface KitEntry {
  path: string;
  kind: "logo" | "palette" | "typography" | "guidelines" | "meta";
  description: string;
  /** Present for text entries this package can generate without an asset store. */
  content?: string;
}

/**
 * What goes in the download (§19).
 *
 * Returns a manifest rather than a zip so the caller decides where bytes come
 * from — generated here for the text, object storage for the images. It also
 * means this stays testable without a storage backend.
 */
export function brandKitManifest(profile: BrandProfile): KitEntry[] {
  const slug = slugify(profile.name) || "brand";
  const palette = JSON.stringify(
    Object.fromEntries(profile.palette.map((c) => [c.role, c.hex])),
    null,
    2,
  );

  return [
    {
      path: `${slug}/logo/${slug}-primary.svg`,
      kind: "logo",
      description: "Primary logo — full lockup, colour",
    },
    { path: `${slug}/logo/${slug}-symbol.svg`, kind: "logo", description: "Symbol only, for avatars and favicons" },
    { path: `${slug}/logo/${slug}-wordmark.svg`, kind: "logo", description: "Wordmark only" },
    {
      path: `${slug}/logo/${slug}-monochrome.svg`,
      kind: "logo",
      description: "One colour — for stamps, embroidery and single-colour printing",
    },
    {
      path: `${slug}/colour/palette.json`,
      kind: "palette",
      description: "Hex codes, machine readable",
      content: palette,
    },
    {
      path: `${slug}/colour/palette.css`,
      kind: "palette",
      description: "CSS custom properties, ready to paste into a site",
      content: paletteCss(profile.palette),
    },
    {
      path: `${slug}/type/typography.txt`,
      kind: "typography",
      description: "Font names and fallbacks",
      content: `Headings: ${profile.typography.primary}\nFallback: ${profile.typography.primaryFallback}\nBody: ${profile.typography.secondary}\nFallback: ${profile.typography.secondaryFallback}\n`,
    },
    {
      path: `${slug}/${slug}-guidelines.md`,
      kind: "guidelines",
      description: "The full guidelines document",
      content: buildGuidelines(profile),
    },
    {
      path: `${slug}/brand.json`,
      kind: "meta",
      description: "The whole brand profile, for import elsewhere",
      content: JSON.stringify(profile, null, 2),
    },
  ];
}

export function paletteCss(palette: readonly ColorSwatch[]): string {
  const lines = palette.map((c) => `  --brand-${c.role}: ${c.hex};`).join("\n");
  return `:root {\n${lines}\n}\n`;
}
